name: CI Hate speech
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  pull-files:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install dvc
            python -m pip install 'dvc[gdrive]'
        - name: DVC pull data
          run: |
            dvc pull
          env:
            GDRIVE_CREDENTIALS_DATA: ${{ secrets.DVCREMOTE }}
        -name: Test files
          run: |
            ls -altr

